### PR TITLE
hotel-booking-frontend: Finalize-Login

### PR DESCRIPTION
**Pull request by Kumilachew-g**
**In this PR, I have done the following tasks.**
- Added redirect after login.
- Created a logged-in state in the redux store.
- Added Add validation for login component.

image

image

### CODE REVIEW

**Review by angeluray — CHANGES_REQUESTED** [review]
## Changes required ♻️ 

Hi @Kumilachew-g, well done on implementing the last changes, however there are a couple of things that you could improve... The project gave me some linter errors for the registration component, please make sure to fix them, then your project will be approved.

image

You can read this link as a guide for solving it ➡️  [link to solve linter error](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/label-has-associated-control.md)

**Comment by Kumilachew-g** [comment]
👋 @angeluray, That is not mine. That is Tadesse's implementation, Anyway I will solve it but there is no such type of errors in my local machine. Please pull the latest "**register.jsx**". It will fix the errors

**Comment by Kumilachew-g** [comment]
👋 **@angeluray,**
On my side, it works just like this.
image

**Review by angeluray — APPROVED** [review]
## STATUS: APPROVE ✅ 

Well done on implementing the last changes. It's time to merge it.

**Pull request merged**
